admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_login:
    pattern:  /login
    defaults: { _controller: AdminBundle:Security:login }

admin_check:
    pattern:  /login_check
    defaults: { _controller: AdminBundle:Security:check }

admin_logout:
    pattern:  /logout
    defaults: { _controller: AdminBundle:Security:logout }
