admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

model:
    resource: "@ModelBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
